[CmdletBinding()]
param()
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$Root=Split-Path -Parent $PSScriptRoot;$Scripts=Join-Path $Root 'scripts';$Monitor=Join-Path $Scripts 'watch_long_task.ps1';$Health=Join-Path $Scripts 'test_monitor_health.ps1';$Supervisor=Join-Path $Scripts 'example_supervisor.ps1';$Run=Join-Path $PSScriptRoot '.runtime';$Count=0;$HostExe=[Diagnostics.Process]::GetCurrentProcess().MainModule.FileName
function Ok{param([bool]$v,[string]$n)if(-not $v){throw "FAIL: $n"};$script:Count++;"PASS: $n"}
function WriteJson{param($p,$o)[IO.File]::WriteAllText($p,($o|ConvertTo-Json -Depth 6),[Text.UTF8Encoding]::new($false))}
function Status{param($state='RUNNING',$processed=$null,$total=$null,$valid=$false,$target=$null,$supervisor=$null)[ordered]@{contract_version='agent-long-task-status-v1';task='test';stage='TEST';state=$state;started_at=[datetimeoffset]::Now.ToString('O');processed=$processed;total=$total;unit='items';target_process_id=$target;supervisor_process_id=$supervisor;checkpoint_state='VALID';artifact_state='PENDING';artifact_validated=$valid;last_error=$null}}
function Heart{param($monitorId,$count=1,$when=([datetimeoffset]::Now),$target=$null,$supervisor=$null)[ordered]@{contract_version='agent-long-task-monitor-health-v1';monitor_process_id=$monitorId;refresh_count=$count;last_refresh_at=$when.ToString('O');observed_state='RUNNING';observed_target_process_id=$target;observed_supervisor_process_id=$supervisor;observed_processed=$null;observed_total=$null}}
function Observe{param($s,$h)$all=& $Monitor -StatusPath $s -HealthPath $h -Once -PassThru 6>&1;$obj=$all|Where-Object{$null -ne $_.PSObject.Properties['progress']}|Select-Object -Last 1;[pscustomobject]@{Object=$obj;Text=($all|Out-String)}}
function Native{param($file,$arguments)$out=Join-Path $Run ([guid]::NewGuid().ToString()+'.out');$err=Join-Path $Run ([guid]::NewGuid().ToString()+'.err');$p=Start-Process -FilePath $HostExe -ArgumentList ($arguments -join ' ') -PassThru -Wait -RedirectStandardOutput $out -RedirectStandardError $err;$text=[IO.File]::ReadAllText($out)+[IO.File]::ReadAllText($err);[pscustomobject]@{Code=$p.ExitCode;Text=$text}}
New-Item -ItemType Directory -Force -Path $Run|Out-Null
try{
  $allps=Get-ChildItem $Scripts -Filter '*.ps1';foreach($f in $allps){$t=$null;$e=$null;[void][Management.Automation.Language.Parser]::ParseFile($f.FullName,[ref]$t,[ref]$e);Ok ($e.Count -eq 0) "parser $($f.Name)"}
  $s=Join-Path $Run 'status.json';$h=Join-Path $Run 'health.json';$checkpoint=Join-Path $Run 'checkpoint.bin';$artifact=Join-Path $Run 'artifact.bin';[IO.File]::WriteAllText($checkpoint,'checkpoint');[IO.File]::WriteAllText($artifact,'artifact')
  WriteJson $s (Status 'RUNNING' 50 100 $false);$before=[IO.File]::ReadAllBytes($s);$o=Observe $s $h;Ok ($o.Object.progress.Exact -and $o.Object.progress.Percent -eq 50) 'exact progress available';Ok (Test-Path $h) 'independent heartbeat written';Ok (([Convert]::ToBase64String($before)) -eq ([Convert]::ToBase64String([IO.File]::ReadAllBytes($s)))) 'status unchanged';Ok (([IO.File]::ReadAllText($checkpoint)) -eq 'checkpoint') 'checkpoint unchanged';Ok (([IO.File]::ReadAllText($artifact)) -eq 'artifact') 'artifact unchanged'
  WriteJson $s (Status 'COMPLETED' 100 100 $true);$o=Observe $s $h;Ok ($o.Text -match 'Percent: 100\.00%') 'completed validated displays 100'
  WriteJson $s (Status 'COMPLETED' $null $null $true);$o=Observe $s $h;Ok (-not($o.Text -match 'Percent:') -and -not($o.Text -match 'ETA:')) 'completed null counters no numeric progress'
  WriteJson $s (Status 'FAILED' $null $null $false);$o=Observe $s $h;Ok ($o.Text -match 'FAILED' -and $o.Text -notmatch 'PASS|COMPLETED') 'failed lifecycle displayed'
  WriteJson $s (Status 'FAILED' 100 100 $false);$o=Observe $s $h;Ok ($o.Text -match 'FAILED' -and $o.Text -notmatch '100\.00%|FINALIZATION PENDING|PASS') 'failed full counters remains failure'
  WriteJson $s (Status 'RUNNING' 1 1 $false 999999 $null);$o=Observe $s $h;Ok ($o.Object.status.state -eq 'RUNNING' -and $o.Object.status.artifact_validated -eq $false) 'missing target does not synthesize pass'
  WriteJson $s (Status 'RUNNING' 101 100 $false);$o=Observe $s $h;Ok (-not $o.Object.progress.Exact -and $o.Text -notmatch 'Percent:|ETA:') 'overflow counters unavailable'
  $bytes=[IO.File]::ReadAllBytes($s);$c=Native $HostExe @('-NoProfile','-File',$Monitor,'-StatusPath',$s,'-HealthPath',$s,'-Once');Ok ($c.Code -ne 0) 'status health collision rejected';Ok (([Convert]::ToBase64String($bytes)) -eq ([Convert]::ToBase64String([IO.File]::ReadAllBytes($s)))) 'collision preserves status bytes'
  $sup=Join-Path $Run 'supervisor.json';$sp=Start-Process -FilePath 'pwsh.exe' -ArgumentList ('-NoProfile -File "'+$Supervisor+'" -FilePath "'+$env:ComSpec+'" -ArgumentList "/c","exit 7" -StatusPath "'+$sup+'"') -PassThru -Wait;$supstate=Get-Content $sup -Raw|ConvertFrom-Json;Ok ($supstate.state -eq 'FAILED' -and $supstate.native_exit_code -eq 7) 'supervisor real exit 7'
  # Health failure matrix: each uses a real externally invoked helper and real wait.
  $live=[Diagnostics.Process]::GetCurrentProcess().Id;$hs=Join-Path $Run 'health-status.json';WriteJson $hs (Status 'RUNNING' $null $null $false 11 22);$hh=Join-Path $Run 'health.json'
  $cases=@(@('stale',(Heart $live 1 ([datetimeoffset]::Now.AddMinutes(-2)) 11 22)),@('malformed','{'),@('wrongtarget',(Heart $live 1 ([datetimeoffset]::Now  ) 99 22)),@('wrongsupervisor',(Heart $live 1 ([datetimeoffset]::Now) 11 99)),@('wrongmonitor',(Heart 999999 1 ([datetimeoffset]::Now) 11 22)),@('zero',(Heart $live 0 ([datetimeoffset]::Now) 11 22)))
  foreach($case in $cases){if($case[1] -is [string]){[IO.File]::WriteAllText($hh,$case[1])}else{WriteJson $hh $case[1]};$r=Native $HostExe @('-NoProfile','-File',$Health,'-StatusPath',$hs,'-HealthPath',$hh,'-MonitorProcessId',$live,'-MonitorLaunchTime',([datetimeoffset]::Now.AddSeconds(-1)).ToString('O'),'-RefreshSeconds','1');Ok ($r.Code -ne 0) ("health rejects "+$case[0])}
  [IO.File]::WriteAllText($hs,'{');WriteJson $hh (Heart $live 1 ([datetimeoffset]::Now) 11 22);$r=Native $HostExe @('-NoProfile','-File',$Health,'-StatusPath',$hs,'-HealthPath',$hh,'-MonitorProcessId',$live,'-MonitorLaunchTime',([datetimeoffset]::Now.AddSeconds(-1)).ToString('O'),'-RefreshSeconds','1');Ok ($r.Code -ne 0) 'health rejects malformed status'
  $dead=Start-Process -FilePath $HostExe -ArgumentList '-NoProfile -Command "exit 0"' -PassThru -Wait;$deadId=$dead.Id;$deadAlive=$false;try{Get-Process -Id $deadId -ErrorAction Stop|Out-Null;$deadAlive=$true}catch{};Ok (-not $deadAlive) 'dead monitor fixture PID confirmed absent';WriteJson $hs (Status 'RUNNING' $null $null $false 11 22);WriteJson $hh (Heart $deadId 1 ([datetimeoffset]::Now) 11 22);$r=Native $HostExe @('-NoProfile','-File',$Health,'-StatusPath',$hs,'-HealthPath',$hh,'-MonitorProcessId',$deadId,'-MonitorLaunchTime',([datetimeoffset]::Now.AddSeconds(-1)).ToString('O'),'-RefreshSeconds','1');Ok ($r.Code -ne 0) 'health rejects genuinely dead monitor process'
  $a=Start-Process -FilePath $HostExe -ArgumentList '-NoProfile -Command "Start-Sleep 1"' -PassThru;$aId=$a.Id;WriteJson $hs (Status 'RUNNING' $null $null $false 11 22);WriteJson $hh (Heart $aId 1 ([datetimeoffset]::Now) 11 22);$a.WaitForExit();$aAlive=$false;try{Get-Process -Id $aId -ErrorAction Stop|Out-Null;$aAlive=$true}catch{};Ok (-not $aAlive) 'previous monitor instance exited';$b=Start-Process -FilePath $HostExe -ArgumentList '-NoProfile -Command "Start-Sleep 10"' -PassThru;try{Ok ($b.Id -ne $aId) 'current monitor instance differs';$r=Native $HostExe @('-NoProfile','-File',$Health,'-StatusPath',$hs,'-HealthPath',$hh,'-MonitorProcessId',$b.Id,'-MonitorLaunchTime',([datetimeoffset]::Now.AddSeconds(-1)).ToString('O'),'-RefreshSeconds','1');Ok ($r.Code -ne 0) 'previous monitor heartbeat rejected for current instance'}finally{if(-not $b.HasExited){Stop-Process -Id $b.Id -Force}}
  # Real monitor + helper success and post-start refresh.
  WriteJson $hs (Status 'RUNNING' $null $null $false $live $null);$realh=Join-Path $Run 'real.health.json';$mon=Start-Process -FilePath $HostExe -ArgumentList ('-NoProfile -File "'+$Monitor+'" -StatusPath "'+$hs+'" -HealthPath "'+$realh+'" -RefreshSeconds 1') -PassThru;try{$start=[datetimeoffset]::Now;$r=Native $HostExe @('-NoProfile','-File',$Health,'-StatusPath',$hs,'-HealthPath',$realh,'-MonitorProcessId',$mon.Id,'-MonitorLaunchTime',$start.ToString('O'),'-RefreshSeconds','1');$real=Get-Content $realh -Raw|ConvertFrom-Json;Ok ($r.Code -eq 0 -and $real.monitor_process_id -eq $mon.Id -and $real.refresh_count -ge 1) 'real monitor health passes after refresh';Ok (([datetimeoffset]::Now-$start).TotalSeconds -ge 1) 'health crossed refresh interval'}finally{if(-not $mon.HasExited){Stop-Process -Id $mon.Id -Force}}
  $terminal=Join-Path $Run 'terminal.json';WriteJson $terminal (Status 'COMPLETED' 1 1 $true);$psi=New-Object Diagnostics.ProcessStartInfo;$psi.FileName=$HostExe;$psi.Arguments='-NoProfile -File "'+$Monitor+'" -StatusPath "'+$terminal+'" -HealthPath "'+(Join-Path $Run 'terminal.health.json')+'" -RefreshSeconds 1';$psi.UseShellExecute=$false;$psi.RedirectStandardInput=$true;$psi.RedirectStandardOutput=$true;$psi.RedirectStandardError=$true;$tp=New-Object Diagnostics.Process;$tp.StartInfo=$psi;[void]$tp.Start();$output=New-Object Text.StringBuilder;$readTask=$tp.StandardOutput.ReadLineAsync();try{$until=[datetime]::UtcNow.AddSeconds(5);while([datetime]::UtcNow -lt $until -and $output.ToString() -notmatch 'Monitoring finished\. Press Enter to close this window\.'){if($readTask.Wait(50)){$line=$readTask.Result;if($null -ne $line){[void]$output.AppendLine($line);$readTask=$tp.StandardOutput.ReadLineAsync()}else{break}}};$prompt=($output.ToString() -match 'Monitoring finished\. Press Enter to close this window\.');Ok $prompt 'terminal ReadHost prompt observed';Ok (-not $tp.HasExited) 'terminal monitor remains alive after ReadHost prompt';$tp.StandardInput.WriteLine();Ok ($tp.WaitForExit(5000) -and $tp.ExitCode -eq 0) 'terminal ReadHost exits normally after Enter'}finally{if(-not $tp.HasExited){Stop-Process -Id $tp.Id -Force}}
  $text=[IO.File]::ReadAllText($Monitor);$alltext=($allps|%{[IO.File]::ReadAllText($_.FullName)})-join "`n";Ok (-not($alltext -match '(?im)^\s*\$(?:pid)\s*=')) 'PID AST/static guard';Ok (-not($text -match 'Stop-Process|Start-Process|\.Kill\(')) 'sidecar control guard';Ok (-not($alltext -match '(?i)-NoExit')) 'NoExit guard';Ok ($text -match 'Read-Host') 'terminal ReadHost path present'
  "Contract tests passed: $Count"
}finally{if(Test-Path $Run){Remove-Item $Run -Recurse -Force}}
